/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasir;
import java.awt.Dimension;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Lenovo
 */
public class FrmBarang extends javax.swing.JFrame {

    /**
     * Creates new form FrmBarang
     */
  DefaultTableModel model = new DefaultTableModel();
  database db = new database ();
  public FrmBarang(){
       initComponents();
       db.koneksi();
       
        Dimension Posisi = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (Posisi.width - this.getWidth()) / 2;
        int y = (Posisi.height - this.getHeight()) /2;
        this.setLocation(x, y);
    
        db.koneksi();
        viewdata();   
    }
    
    
    
    public void viewdata() {
        model.addColumn("kode");
        model.addColumn("Nama Barang");
        model.addColumn("Harga");
        model.addColumn("Jumlah");
        model.addColumn("Kategori");
        
        try {
            ResultSet rs=db.ambildata("select * from tb_barang");
            while (rs.next()) {
                model.addRow(new Object[] {rs.getString("id_barang"),rs.getString("nm_barang"),rs.getString("jml_barang"),rs.getString("hrg_barang"),rs.getString("kategori")});
                jTable1.setModel(model);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Debug", JOptionPane.ERROR_MESSAGE);
        }
    
    }
     private void isianBersih(){
            jid_brg.setText("");
            jnm_barang.setText("");
            jjml_barang.setText("");
            jhrg_jual.setText("");
            jhrg_beli.setText("");
            jc_ktgr.setSelectedItem("");

           }


    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jid_brg = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jnm_barang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jjml_barang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jhrg_jual = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jhrg_beli = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jc_ktgr = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jbt_simpan = new javax.swing.JButton();
        jbt_edit = new javax.swing.JButton();
        jbt_hapus = new javax.swing.JButton();
        jbt_keluar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel1.setText("FORM BARANG");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, 40));

        jid_brg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jid_brgActionPerformed(evt);
            }
        });
        getContentPane().add(jid_brg, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 233, 30));

        jLabel2.setText("Kode Barang");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, 20));
        getContentPane().add(jnm_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 233, 30));

        jLabel3.setText("Nama Barang");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, 20));
        getContentPane().add(jjml_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 232, 30));

        jLabel4.setText("Jumlah Barang");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, 20));
        getContentPane().add(jhrg_jual, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 233, 30));

        jLabel5.setText("Harga Barang");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 83, 20));
        getContentPane().add(jhrg_beli, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 232, 30));

        jLabel6.setText("Harga  Beli");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, 20));

        jc_ktgr.setBackground(new java.awt.Color(255, 153, 153));
        jc_ktgr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Minuman", "Sembako" }));
        jc_ktgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc_ktgrActionPerformed(evt);
            }
        });
        getContentPane().add(jc_ktgr, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, -1, 20));

        jLabel7.setText("Kategori");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 74, 20));

        jbt_simpan.setBackground(new java.awt.Color(255, 102, 102));
        jbt_simpan.setForeground(new java.awt.Color(255, 255, 255));
        jbt_simpan.setText("Simpan");
        jbt_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_simpanActionPerformed(evt);
            }
        });
        getContentPane().add(jbt_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, -1, -1));

        jbt_edit.setBackground(new java.awt.Color(255, 102, 102));
        jbt_edit.setForeground(new java.awt.Color(255, 255, 255));
        jbt_edit.setText("Edit");
        jbt_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_editActionPerformed(evt);
            }
        });
        getContentPane().add(jbt_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, -1, -1));

        jbt_hapus.setBackground(new java.awt.Color(255, 102, 102));
        jbt_hapus.setForeground(new java.awt.Color(255, 255, 255));
        jbt_hapus.setText("Hapus");
        jbt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_hapusActionPerformed(evt);
            }
        });
        getContentPane().add(jbt_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, -1, -1));

        jbt_keluar.setBackground(new java.awt.Color(255, 102, 102));
        jbt_keluar.setForeground(new java.awt.Color(255, 255, 255));
        jbt_keluar.setText("Keluar");
        jbt_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_keluarActionPerformed(evt);
            }
        });
        getContentPane().add(jbt_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 440, -1, -1));

        jPanel2.setBackground(new java.awt.Color(233, 165, 179));

        jButton3.setBackground(new java.awt.Color(61, 3, 1));
        jButton3.setFont(new java.awt.Font("Cambria Math", 1, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Laporan STOK");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logo3.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama Barang", "Harga", "Jumlah", "Kategori"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 530, 118));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bg.jpeg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 790, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_simpanActionPerformed
        // TODO add your handling code here:

        try {
            ResultSet rs = db.ambildata("select * from tb_barang where id_barang='" + jid_brg.getText() + "'");
            if (rs.next()) {
                JOptionPane.showMessageDialog(null,"Data telah terdaftar");
                jnm_barang.setText( rs.getString("nm_barang"));
                jjml_barang.setText( rs.getString( "jml_barang"));
                jhrg_jual.setText( rs.getString( "hrg_barang"));
                jhrg_jual.setText( rs.getString( "hrg_beli"));
                jc_ktgr.setSelectedItem(rs.getString( "kategori"));

            }else{
                db.aksi("insert into tb_barang(id_barang,nm_barang,kategori,jml_barang,hrg_barang,hrg_beli)values('"+jid_brg.getText()+"','"+jnm_barang.getText()+"','"+jc_ktgr.getSelectedItem()+"','"+jjml_barang.getText()+"','"+jhrg_jual.getText()+"','"+jhrg_beli.getText()+"')");
                JOptionPane.showMessageDialog(null,"Data telah Disimpan");
                jid_brg.setText("");
                jnm_barang.setText("");
                jjml_barang.setText("");
                jhrg_jual.setText("");
                jhrg_beli.setText("");
                jc_ktgr.setSelectedItem("");

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jbt_simpanActionPerformed

    private void jbt_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_editActionPerformed
        // TODO add your handling code here:
        try {
            ResultSet rs = db.ambildata("SELECT * FROM tb_barang WHERE id_barang='" + jid_brg.getText() + "'");
            if (rs.next()) {
                db.aksi("update tb_barang set "
                    + "nm_barang='" + jnm_barang.getText() + "', "
                    + "jml_barang='" + jjml_barang.getText() + "', "
                    + "kategori='" + jc_ktgr.getSelectedItem() + "', "
                    + "hrg_barang='" + jhrg_jual.getText() + "', "
                    + "hrg_beli='" + jhrg_beli.getText() + "' "
                    + "WHERE id_barang='" + jid_brg.getText() + "'");
                JOptionPane.showMessageDialog( null,"Data Berhasil Diedit");
            }else{
                JOptionPane.showMessageDialog( null,"Tidak ada data yang hendak di edit...");
            }
            jid_brg.requestFocus();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jbt_editActionPerformed

    private void jbt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_hapusActionPerformed
        // TODO add your handling code here:
        try {
            ResultSet rs=db.ambildata("select * from tb_barang where id_barang='"+jid_brg.getText()+"'");
            if (rs.next()) {
                int n =  JOptionPane.showConfirmDialog( this, "Anda Yakin?", "Hilda Massage",
                    JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE, null );
                if (n == JOptionPane.YES_OPTION) {
                    db.aksi("delete from tb_barang where id_barang='"+jid_brg.getText()+"'");
                    JOptionPane.showMessageDialog( null, "Data Sudah terhapus");
                }
            }else{
                JOptionPane.showMessageDialog( null, "Data tidak terdaftar");
            }
            jid_brg.setText("");
            jnm_barang.setText("");
            jjml_barang.setText("");
            jhrg_jual.setText("");
            jhrg_beli.setText("");
            jc_ktgr.setSelectedItem("");

            jid_brg.requestFocus();

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jbt_hapusActionPerformed

    private void jbt_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_keluarActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog( null, "Yakin keluar dari aplikasi ini?",
            "Reminder Hilda",JOptionPane.YES_NO_OPTION);
        if (x ==JOptionPane.YES_OPTION){
            this.dispose();  }
    }//GEN-LAST:event_jbt_keluarActionPerformed

    private void jc_ktgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc_ktgrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jc_ktgrActionPerformed

    private void jid_brgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jid_brgActionPerformed
        // TODO add your handling code here:
        try {

            ResultSet rs=db.ambildata("select * from tb_barang where id_barang='" + jid_brg.getText() + "'");
            if (rs.next()) {
                jnm_barang.setText( rs.getString("nm_barang"));
                jjml_barang.setText(rs.getString("jml_barang"));
                jhrg_jual.setText( rs.getString("hrg_barang"));
                jhrg_beli.setText( rs.getString("hrg_beli"));
                jc_ktgr.setSelectedItem(rs.getString("kategori"));
                jbt_simpan.setEnabled(false);
                // Simpan.setEnabled(false);
                // hapus.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog( null, "Data Belum terdaftar, tambahkan");
                jnm_barang.requestFocus();

            }
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_jid_brgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbt_edit;
    private javax.swing.JButton jbt_hapus;
    private javax.swing.JButton jbt_keluar;
    private javax.swing.JButton jbt_simpan;
    private javax.swing.JComboBox<String> jc_ktgr;
    private javax.swing.JTextField jhrg_beli;
    private javax.swing.JTextField jhrg_jual;
    private javax.swing.JTextField jid_brg;
    private javax.swing.JTextField jjml_barang;
    private javax.swing.JTextField jnm_barang;
    // End of variables declaration//GEN-END:variables
}
