/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kasir;

/**
 *
 * @author LENOVO
 */
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;


public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    // Objek database
    database db = new database();

    public FrmLogin() {
        initComponents();

        // Mengatur posisi tengah layar
        Dimension Posisi = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (Posisi.width - this.getWidth()) / 2;
        int y = (Posisi.height - this.getHeight()) / 2;
        this.setLocation(x, y);

        // Hubungkan ke database
        db.koneksi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPassword = new javax.swing.JTextField();
        jLogin = new javax.swing.JButton();
        jLoginkasir = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logo 2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel8)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 410));

        jLabel2.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(116, 76, 77));
        jLabel2.setText("SELAMAT DATANG");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 230, -1));

        jLabel1.setForeground(new java.awt.Color(116, 76, 77));
        jLabel1.setText("Silahkan Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, -1, -1));

        jUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(jUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 220, 30));

        jLabel3.setText("Username");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 220, 30));

        jLogin.setBackground(new java.awt.Color(255, 102, 102));
        jLogin.setText("LOGIN");
        jLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, -1));

        jLoginkasir.setBackground(new java.awt.Color(204, 204, 204));
        jLoginkasir.setText("Login Sebagai Kasir");
        jLoginkasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginkasirActionPerformed(evt);
            }
        });
        getContentPane().add(jLoginkasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bg.jpeg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 370, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUsernameActionPerformed

    private void jLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginActionPerformed
        // TODO add your handling code here:
        try {
            // Query untuk memeriksa username dan password
            ResultSet rs = db.ambildata(
                "SELECT * FROM user WHERE username='" + jUsername.getText() + "' AND password='" + jPassword.getText() + "'"
            );

            if (rs.next()) {
                // Jika login berhasil, buka menu utama
                dispose();
                new Menu_Utama_Owner().setVisible(true);
            } else {
                // Atur warna untuk pop-up
                UIManager.put("Panel.background", new ColorUIResource(255, 182, 193)); // Pink muda
                UIManager.put("OptionPane.background", new ColorUIResource(255, 182, 193)); // Pink muda
                UIManager.put("Button.background", new ColorUIResource(255, 105, 180)); // Pink tua
                

                int pilihan = JOptionPane.showOptionDialog(
                    null,
                    "Username atau Password salah. Silahkan pilih opsi berikut!",
                    "Login Gagal",
                    JOptionPane.YES_NO_CANCEL_OPTION,
                    JOptionPane.ERROR_MESSAGE,
                    null,
                    new Object[]{"Coba Lagi", "Ganti Username/Password", "Keluar"},
                    "Coba Lagi"
                );

                // Tindak lanjut berdasarkan pilihan pengguna
                if (pilihan == JOptionPane.YES_OPTION) {
                    // Reset form login
                    jUsername.setText("");
                    jPassword.setText("");
                    jUsername.requestFocus();
                } else if (pilihan == JOptionPane.NO_OPTION) {
                    // Buka dialog ganti username dan password
                    gantiUsernamePassword();
                } else if (pilihan == JOptionPane.CANCEL_OPTION) {
                    // Tutup aplikasi
                    System.exit(0);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jLoginActionPerformed

    private void jLoginkasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginkasirActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jLoginkasirActionPerformed
    
    private void gantiUsernamePassword() {
    String newUsername = JOptionPane.showInputDialog(null, "Masukkan Username Baru:");
    String newPassword = JOptionPane.showInputDialog(null, "Masukkan Password Baru:");

    if (newUsername != null && newPassword != null && !newUsername.trim().isEmpty() && !newPassword.trim().isEmpty()) {
      try {
        // Eksekusi query untuk menyimpan data
        db.aksi("INSERT INTO tb_login (username, password) VALUES ('" + newUsername + "', '" + newPassword + "')");
        JOptionPane.showMessageDialog(null, "Data telah Disimpan");
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
        e.printStackTrace(); // Cetak error untuk debugging
    }
} else {
    JOptionPane.showMessageDialog(null, "Username dan Password baru tidak boleh kosong!");
}
}

   
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jLogin;
    private javax.swing.JTextField jLoginkasir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jPassword;
    private javax.swing.JTextField jUsername;
    // End of variables declaration//GEN-END:variables
}
