/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kasir;

/**
 *
 * @author LENOVO
 */
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.table.*;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class FrmTransjual extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    DefaultTableModel model = new DefaultTableModel();
    long sumTotal = 0;
    
    //panggil database
    database db = new database();
    
    public FrmTransjual() {
        initComponents();
        
        db.koneksi();
        initComponents();
        
        Dimension Posisi = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (Posisi.width - this.getWidth()) /2;
        int y = (Posisi.height - this.getHeight()) /2;
        this.setLocation(x, y);
        
        //tampilkan nomor transaksi
        buatnomor();
        //tampilkan tanggal transaksi
        setCurrentDate();
        //tampilkan tabel
        aturTabel();
    }

    public void setCurrentDate() {
        Date currentDate = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd MMMM yyyy");
        jTanggal.setText(dateFormat.format(currentDate));
    }
    
    public void buatnomor(){
        try {
            ResultSet rs = db.ambildata("Select no_trans as auto from tbtrans_jual ORDER by no_trans desc");
            
            if (rs.next()){
                int no_urut = Integer.parseInt(rs.getString("auto")) + 1;
                jNoTrans.setText(Integer.toString(no_urut));
            } else {
                int not_t = 1;
                jNoTrans.setText(Integer.toString(not_t));
            }
            rs.close();
        } catch (Exception e) {
        }
    }
    
    //perintah membuat judul tabel pada form transaksi jual
    public void aturTabel(){
        model.addColumn("KODE BARANG");
        model.addColumn("NAMA BARANG");
        model.addColumn("HARGA BARANG");
        model.addColumn("JUMLAH BARANG");
        jTable1.setModel(model);
    }
    
    private void isianBersih(){
        jKodeBarang.setText("");
        jNamaBarang.setText("");
        jStok.setText("");
        jHarga.setText("");
        jBeli.setText("");
        jJumlahHarga.setText("");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jNoTrans = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTanggal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jKodeBarang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jNamaBarang = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jBeli = new javax.swing.JTextField();
        jStok = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jHarga = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jJumlahHarga = new javax.swing.JTextField();
        jTambah = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtotal = new javax.swing.JTextField();
        jbayar = new javax.swing.JTextField();
        jkembalian = new javax.swing.JTextField();
        jHapus = new javax.swing.JButton();
        jCetakNota = new javax.swing.JButton();
        jSimpan = new javax.swing.JButton();
        jKeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(233, 165, 179));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBackground(new java.awt.Color(61, 3, 1));
        jButton6.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Tambah User");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 170, 45));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logo3.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 180, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 500));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, -1, -1));

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel1.setText("TRANSAKSI PENJUALAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        jLabel2.setText("NO TRANSAKSI");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, 20));

        jNoTrans.setBackground(new java.awt.Color(0, 0, 0));
        jNoTrans.setForeground(new java.awt.Color(51, 255, 51));
        jNoTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNoTransActionPerformed(evt);
            }
        });
        getContentPane().add(jNoTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 100, -1));

        jLabel4.setText("TANGGAL");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, -1, -1));
        getContentPane().add(jTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 60, 110, -1));

        jLabel5.setText("KODE BARANG");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        jKodeBarang.setBackground(new java.awt.Color(0, 0, 0));
        jKodeBarang.setForeground(new java.awt.Color(51, 255, 51));
        jKodeBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKodeBarangActionPerformed(evt);
            }
        });
        getContentPane().add(jKodeBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 90, -1));

        jLabel6.setText("NAMA BARANG");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));
        getContentPane().add(jNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 170, -1));

        jLabel7.setText("JUMLAH");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 100, -1, -1));

        jLabel8.setText("STOK");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, -1, -1));

        jBeli.setBackground(new java.awt.Color(0, 0, 0));
        jBeli.setForeground(new java.awt.Color(51, 255, 51));
        jBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliActionPerformed(evt);
            }
        });
        getContentPane().add(jBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 130, 80, -1));
        getContentPane().add(jStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 80, -1));

        jLabel9.setText("HARGA");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, -1, 20));
        getContentPane().add(jHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 110, -1));

        jLabel10.setText("JUMLAH HARGA");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, -1, 20));
        getContentPane().add(jJumlahHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 170, 120, -1));

        jTambah.setBackground(new java.awt.Color(255, 102, 102));
        jTambah.setForeground(new java.awt.Color(255, 255, 255));
        jTambah.setText("TAMBAH");
        jTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTambahActionPerformed(evt);
            }
        });
        getContentPane().add(jTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 200, -1, -1));

        jLabel11.setText("PILIH BARANG YANG AKAN DIBATALKAN");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        jLabel12.setText("TOTAL");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, -1, -1));

        jLabel13.setText("BAYAR");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, -1, -1));

        jLabel14.setText("KEMBALI");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 60, 20));
        getContentPane().add(jtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 80, 40));

        jbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbayarActionPerformed(evt);
            }
        });
        getContentPane().add(jbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, 80, 40));
        getContentPane().add(jkembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 80, 40));

        jHapus.setBackground(new java.awt.Color(255, 102, 102));
        jHapus.setForeground(new java.awt.Color(255, 255, 255));
        jHapus.setText("HAPUS");
        jHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHapusActionPerformed(evt);
            }
        });
        getContentPane().add(jHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, -1, -1));

        jCetakNota.setBackground(new java.awt.Color(255, 102, 102));
        jCetakNota.setForeground(new java.awt.Color(255, 255, 255));
        jCetakNota.setText("CETAK NOTA");
        getContentPane().add(jCetakNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 400, -1, -1));

        jSimpan.setBackground(new java.awt.Color(255, 102, 102));
        jSimpan.setForeground(new java.awt.Color(255, 255, 255));
        jSimpan.setText("SIMPAN");
        jSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(jSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 450, -1, -1));

        jKeluar.setBackground(new java.awt.Color(255, 102, 102));
        jKeluar.setForeground(new java.awt.Color(255, 255, 255));
        jKeluar.setText("KELUAR");
        jKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(jKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 450, -1, -1));

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(51, 255, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "KODE BARANG", "NAMA BARANG", "JUMLAH BARANG", "HARGA BARANG"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 750, 130));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bg.jpeg"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 790, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSimpanActionPerformed
        // TODO add your handling code here:
        sumTotal = 0;
        int row = jTable1.getRowCount();
        
        try {
            ResultSet rs=db.ambildata("select * from trans_jual where no_transjual ='"+jNoTrans.getText()+"'");
            if (rs.next()){
                JOptionPane.showMessageDialog(null, "No transaksi sudah terdaftar");
            }else{
                for (int i = 0; i < row; i++){
                    db.aksi("INSERT INTO tbdetail_jual(no_trans,tanggal,id_barang,jml_barang,hrg_barang)values" 
                     + "('" + jNoTrans.getText() + "','" + jTanggal.getText() + "','" + jTable1.getValueAt(i, 0) + "',"
                             + "'" + jTable1.getValueAt(i, 3) + "','" + jTable1.getValueAt(i, 2) + "')");
                    db.aksi("update tb_barang set jml_barang=jml_barang-" + jTable1.getValueAt(i, 3) + " where id_barang='" +
                            jTable1.getValueAt(i, 0) + "'");
                }
                db.aksi("insert into trans_jual (no_transjual,tanggal,total_harga)values('" + jNoTrans.getText() + "'," 
                        + "'" + jNoTrans.getText() + "','" + jtotal.getText() + "')");
                JOptionPane.showMessageDialog(null, "Data telah tersimpan");
                
                //}
                model.setRowCount(0);
                buatnomor();
                // } catch (Exception e) {
                // JOptionPane.showMessageDialog(null, e);
                
            }} catch (SQLException ex) {
                Logger.getLogger(FrmTransjual.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jSimpanActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jNoTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNoTransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNoTransActionPerformed

    private void jbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbayarActionPerformed
        // TODO add your handling code here:
         int b1, b2, kembalian, bayar = Integer.parseInt(jbayar.getText());
        b1 = Integer.parseInt(jbayar.getText());
        b2 = Integer.parseInt(jtotal.getText());
        kembalian = b1 - b2;
        jkembalian.setText(String.valueOf(kembalian));
    }//GEN-LAST:event_jbayarActionPerformed

    private void jKodeBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKodeBarangActionPerformed
        // TODO add your handling code here:
        try {
            ResultSet rs = db.ambildata("select * from tb_barang where id_barang='" +jKodeBarang.getText()+"'");
             if (rs.next()) {
                 jNamaBarang.setText(rs.getString("nm_barang"));
                 jHarga.setText(rs.getString("hrg_barang"));
                 jStok.setText(rs.getString("jml_barang"));
                 jBeli.requestFocus();
             }else{
                 JOptionPane.showMessageDialog(null, "Kode Belum terdaftar");
                 jKodeBarang.selectAll();
             }       
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jKodeBarangActionPerformed

    private void jBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliActionPerformed
        // TODO add your handling code here:
        int a1, a2, total, stok_barang = Integer.parseInt(jStok.getText());
        if (stok_barang > 1) {
            a1 = Integer.parseInt(jHarga.getText());
            a2 = Integer.parseInt(jBeli.getText());
            total = a1 * a2;
            jJumlahHarga.setText(String.valueOf(total));
            jTambah.requestFocus();
    }else{
            JOptionPane.showMessageDialog(null, "Maaf, \nstok sudah mencapai stok minimum!");   
        }
    }//GEN-LAST:event_jBeliActionPerformed

    private void jTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTambahActionPerformed
        // TODO add your handling code here:
        try {
            //konfirmasi tambah
         int n = JOptionPane.showConfirmDialog(this, "Tambah lagi?", "Dia Risky Ananda",
                 JOptionPane.YES_NO_OPTION,
                 JOptionPane.QUESTION_MESSAGE, null);
         if (n == JOptionPane.YES_OPTION){
             long qyt, hrg;
             
             model.addRow(new Object[]{jKodeBarang.getText(), jNamaBarang.getText(), jHarga.getText(), jBeli.getText()});
             jTable1.setModel(model);
             qyt = Long.parseLong(jBeli.getText());
             hrg = Long.parseLong(jHarga.getText());
             sumTotal += (hrg * qyt);
             jJumlahHarga.setText(String.valueOf(sumTotal));
             jKodeBarang.requestFocus();
             jKodeBarang.setText("");
             jNamaBarang.setText("");
             jHarga.setText("");
             jBeli.setText("");
             jJumlahHarga.setText("");
         }else if (n == JOptionPane.NO_OPTION){
             long qyt, hrg;
             model.addRow(new Object[]{jKodeBarang.getText(), jNamaBarang.getText(), jHarga.getText(), jBeli.getText()});
             jTable1.setModel(model);
             qyt = Long.parseLong(jBeli.getText());
             hrg = Long.parseLong(jHarga.getText());
             sumTotal += (hrg * qyt);
             jJumlahHarga.setText(String.valueOf(sumTotal));
             jKodeBarang.requestFocus();
             jKodeBarang.setText("");
             jNamaBarang.setText("");
             jHarga.setText("");
             jBeli.setText("");
             jJumlahHarga.setText("");
             jbayar.requestFocus();
             
         }else{
             jbayar.requestFocus();
         }
        } catch (Exception e) {
        }
    
    }//GEN-LAST:event_jTambahActionPerformed

    private void jHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHapusActionPerformed
        // TODO add your handling code here:
        isianBersih();
    }//GEN-LAST:event_jHapusActionPerformed

    private void jKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTransjual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTransjual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTransjual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTransjual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTransjual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jBeli;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jCetakNota;
    private javax.swing.JButton jHapus;
    private javax.swing.JTextField jHarga;
    private javax.swing.JTextField jJumlahHarga;
    private javax.swing.JButton jKeluar;
    private javax.swing.JTextField jKodeBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNamaBarang;
    private javax.swing.JTextField jNoTrans;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSimpan;
    private javax.swing.JTextField jStok;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jTambah;
    private javax.swing.JTextField jTanggal;
    private javax.swing.JTextField jbayar;
    private javax.swing.JTextField jkembalian;
    private javax.swing.JTextField jtotal;
    // End of variables declaration//GEN-END:variables
}
