/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kasir;

import java.awt.Dimension;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class FrmUser extends javax.swing.JFrame {
    DefaultTableModel model = new DefaultTableModel();
  database db = new database ();
    /**
     * Creates new form FrmUser
     */
    
    public FrmUser() {
        initComponents();
        Dimension Posisi = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (Posisi.width - this.getWidth())/2;
        int y = (Posisi.height - this.getHeight())/2;
        this.setLocation(x,y);
        
        // menghubungkan ke database
        db.koneksi();
        viewdata();
    }

    public void viewdata() {
        model.addColumn("ID USER");
        model.addColumn("NAMA USER");
        model.addColumn("USERNAME");
        model.addColumn("PASSWORD");
        
        try {
            ResultSet rs=db.ambildata("select * from user");
            while (rs.next()) {
                model.addRow(new Object[] {rs.getString("id_user"),rs.getString("nm_user"),rs.getString("username"),rs.getString("password")});
                jTabel.setModel(model);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Debug", JOptionPane.ERROR_MESSAGE);
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jId_User = new javax.swing.JTextField();
        jNama = new javax.swing.JTextField();
        jUsername = new javax.swing.JTextField();
        jPassword = new javax.swing.JTextField();
        jCari = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jEdit = new javax.swing.JButton();
        jHapus = new javax.swing.JButton();
        jSimpan = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabel = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel1.setText("FORM USER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 150, 31));

        jPanel1.setBackground(new java.awt.Color(233, 165, 179));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(61, 3, 1));
        jButton1.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Tambah User");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, 240, 170, 45));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logo3.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 180, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        jLabel2.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel2.setText("ID USER");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel3.setText("NAMA USER");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel4.setText("USERNAME");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel5.setText("PASSWORD");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        jId_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jId_UserActionPerformed(evt);
            }
        });
        getContentPane().add(jId_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 150, -1));
        getContentPane().add(jNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 150, -1));
        getContentPane().add(jUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 150, -1));

        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 150, -1));

        jCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCariActionPerformed(evt);
            }
        });
        getContentPane().add(jCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 100, 20));

        jLabel6.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jLabel6.setText("CARI");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, 30));

        jEdit.setBackground(new java.awt.Color(255, 102, 102));
        jEdit.setForeground(new java.awt.Color(255, 255, 255));
        jEdit.setText("EDIT");
        jEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditActionPerformed(evt);
            }
        });
        getContentPane().add(jEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, -1, -1));

        jHapus.setBackground(new java.awt.Color(255, 102, 102));
        jHapus.setForeground(new java.awt.Color(255, 255, 255));
        jHapus.setText("HAPUS");
        jHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHapusActionPerformed(evt);
            }
        });
        getContentPane().add(jHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, -1, -1));

        jSimpan.setBackground(new java.awt.Color(255, 102, 102));
        jSimpan.setForeground(new java.awt.Color(255, 255, 255));
        jSimpan.setText("SIMPAN");
        jSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(jSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, -1, -1));

        jButton4.setBackground(new java.awt.Color(255, 102, 102));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("KELUAR");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, -1, -1));

        jTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID USER", "NAMA USER", "USERNAME", "PASSWORD"
            }
        ));
        jScrollPane1.setViewportView(jTabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 410, 120));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bg.jpeg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jId_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jId_UserActionPerformed
        // TODO add your handling code here:
        try {
              ResultSet rs=db.ambildata("select * from user where id_user='"+jId_User.getText()+"'");
               if (rs.next()){
                jNama.setText(rs.getString("nm_user"));
                jUsername.setText(rs.getString("username"));
                jPassword.setText(rs.getString("password"));
                jSimpan.setEnabled(false);
                
            }else{
                JOptionPane.showMessageDialog(null, "Data Belum terdaftar silahkan di tambahkan");
            }
        } catch (Exception e) {
        }
                          
    }//GEN-LAST:event_jId_UserActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCariActionPerformed

    private void jSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSimpanActionPerformed
        // TODO add your handling code here:
        
         try {
            ResultSet rs=db.ambildata("select * from user where id_user='"+jId_User.getText() + "'");
            if (rs.next()) {
                JOptionPane.showMessageDialog(null,"Data telah terdaftar");
                jNama.setText( rs.getString("nm_user"));
                jUsername.setText( rs.getString("username"));
                jPassword.setText(rs.getString("password"));

            }else{
                String query = "INSERT INTO user (id_user, nm_user, username, password) VALUES ('" +
                            jId_User.getText() + "', '" + 
                            jNama.getText() + "', '" + 
                            jUsername.getText() + "', '" + 
                            jPassword.getText() + "')";
                    boolean success = db.aksi(query);
                    if (success) {
                JOptionPane.showMessageDialog(null, "Data telah Disimpan");
                jId_User.setText("");
                jNama.setText("");
                jUsername.setText("");
                jPassword.setText("");
            }
        
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
       
    }//GEN-LAST:event_jSimpanActionPerformed

    private void jEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditActionPerformed
        // TODO add your handling code here:
         try {
            ResultSet rs = db.ambildata("SELECT * FROM tb_barang WHERE id_barang='" + jId_User.getText() + "'");
            if (rs.next()) {
                db.aksi("update user set "
                    + "nm_barang='" + jnm_barang.getText() + "', "
                    + "jml_barang='" + jjml_barang.getText() + "', "
                    + "kategori='" + jc_ktgr.getSelectedItem() + "', "
                    + "hrg_barang='" + jhrg_jual.getText() + "', "
                    + "hrg_beli='" + jhrg_beli.getText() + "' "
                    + "WHERE id_barang='" + jid_brg.getText() + "'");
                JOptionPane.showMessageDialog( null,"Data Berhasil Diedit");
            }else{
                JOptionPane.showMessageDialog( null,"Tidak ada data yang hendak di edit...");
            }
            jid_brg.requestFocus();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }

    }//GEN-LAST:event_jEditActionPerformed

    private void jHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHapusActionPerformed
        // TODO add your handling code here:
        try {
            ResultSet rs=db.ambildata("select * from user where id_user='"+jId_User.getText()+"'");
            if (rs.next()) {
                int n =  JOptionPane.showConfirmDialog( this, "Anda Yakin?", "Hilda Massage",
                    JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE, null );
                if (n == JOptionPane.YES_OPTION) {
                    db.aksi("delete from user where id_user='"+jId_User.getText()+"'");
                    JOptionPane.showMessageDialog( null, "Data Sudah terhapus");
                }
            }else{
                JOptionPane.showMessageDialog( null, "Data tidak terdaftar");
            }
            jId_User.setText("");
            jNama.setText("");
            jUsername.setText("");
            jPassword.setText("");

            jId_User.requestFocus();

        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_jHapusActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JTextField jCari;
    private javax.swing.JButton jEdit;
    private javax.swing.JButton jHapus;
    private javax.swing.JTextField jId_User;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jNama;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jPassword;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSimpan;
    private javax.swing.JTable jTabel;
    private javax.swing.JTextField jUsername;
    // End of variables declaration//GEN-END:variables
}
